backend:
  ### Below lines for github or gitlab
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  ### Enable below lines when using bitbucket (refer to docs https://www.netlifycms.org/docs/bitbucket-backend/)
  # name: bitbucket
  # repo: owner-name/repo-name # Path to your Bitbucket repository
  ### Enable below lines for login with github
  # name: github
  # repo: emcog/skeleventy-plus



media_folder: "./images"
public_folder: "./dist/images"



# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true



### Allow drafts to be saved
publish_mode: editorial_workflow



collections:
  - label: "Blog"
    name: "blog"
    folder: "blog/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish date", name: "date", widget: "datetime" }
      - { label: "Featured image", name: "featured_image", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  #     - widget: select
  #       label: "tags"
  #       name: "tags"
  #       multiple: true
  #       create: true
  #       options: ["Tags", "created", "from", "config.yml"]
  # - label: "Settings"
  #   name: "settings"
  #   editor:
  #     preview: false
  #   files:
  #     - label: "Navigation"
  #       name: "items"
  #       file: "./site/globas/navigation.json"
  #       fields:
  #         - label: Nav Items
  #           name: main
  #           widget: list
  #           allow_add: false
  #           collapsed: false
  #           fields:
  #             - { label: Title, name: label, widget: string }
  #             - { label: URL, name: url, widget: string }
      # - label: "Global meta settings"
      #   name: "settings"
      #   file: "site/globals/site.json"
      #   fields:
      #     - { label: Name, name: name, widget: string }
      #     - { label: domain, name: url, widget: string }
      #     author:
      #       fields:
      #     - { label: Name,   name: name,   widget: string }
      #     - { label: Email,  name: email,  widget: string }
      #     - { label: Handle, name: handle, widget: string }
      #     - { label: Avatar, name: avata,  widget: url }
      #     social_links:
      #       fields:
      #     - { label: Facebook, name: facebook, widget: string }
      #     - { label: Twitter,  name: twitter, widget: string }
      #     - { label: Linkedin, name: linkedin, widget: string }
      #     address:
      #       fields:
      #     - { label: Number/Name, name: number, widget: string }
      #     - { label: Street,      name: street, widget: string }
      #     - { label: City,        name: city, widget: string }
      #     - { label: Postcode,    name: postcode, widget: string }
      #     - { label: Country,    name: country, widget: string }
      #     contact:
      #       fields:
      #     - { label: Phone,   name: phone,   widget: string }
      #     - { label: Mobile,  name: mobile,  widget: string }
      #     - { label: Email,   name: email,   widget: string }